// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, port;

  express = require('express');

  app = express();

  app.get('/', function(req, res) {
    return res.send('Hello World!');
  });

  port = Number(process.env.PORT || 5000);

  app.listen(port, function() {
    return console.log('Listening on ' + port);
  });

}).call(this);
